version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory:  ~/store-api

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - store_test_results:
                path: build/test-results/test

      - store_artifacts:
                path: build/test-results/test
                when: always

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn package